name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: "6.0"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Package
        run: swift build --configuration release

      - name: Run Tests
        run: swift test
